
version: "3"

services:

  db:
    image: postgres
    container_name: db
    env_file: ./api/.env
    ports:
      - 5432:5432

  redis:
    image: redis
    container_name: redis
    ports:
      - 6739:6739

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: webapp
    restart: always
    depends_on: 
      - db
      - api
      - redis
      - classifier
    volumes:
      - ./webapp:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    env_file: ./api/.env
    restart: always
    depends_on: 
      - db
    ports:
      - 3001:3001
    volumes:
      - shared-volume:/app/audio_files

  classifier:
    build:
      context: ./classifier
      dockerfile: Dockerfile
    container_name: classifier
    env_file: ./classifier/.env
    restart: always
    depends_on: 
      - db
      - api
      - redis
    volumes:
      - shared-volume:/app/audio_files

volumes:
  shared-volume: